#ifndef CYD_UI_FONTS_H
#define CYD_UI_FONTS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Anti-aliased UI fonts, subset to the characters the firmware actually shows.
 *
 * Every table here is const and stays in flash. Nothing is copied to RAM when a
 * font is used, which is the reason these are not LovyanGFX VLW fonts: the VLW
 * loader copies 9 bytes of metrics per glyph to the heap, and the text faces
 * carry several hundred glyphs each.
 *
 * The tables are generated by scripts/ui_fonts/gen_ui_fonts.py and must not be
 * edited by hand. A firmware build fails if a string literal uses a character
 * the text faces do not contain; rerun the generator when that happens.
 *
 * English contract:
 *  - `codepoints` is sorted ascending so a glyph can be found by binary search.
 *  - Bitmaps are 4 bits per pixel, high nibble first, rows packed back to back
 *    with no row padding; a glyph's run starts on a byte boundary.
 *  - `y_offset` is the distance from the top of the line box to the top of the
 *    glyph bitmap. The line box is `line_height` tall with the baseline at
 *    `ascent`, so text can be centred without per-string measurement.
 */

typedef struct {
    uint32_t bitmap_offset;
    uint8_t width;
    uint8_t height;
    uint8_t x_advance;
    int8_t x_offset;
    int8_t y_offset;
} cyd_ui_font_glyph_t;

typedef struct {
    const char *name;
    uint8_t pixel_size;
    uint8_t ascent;
    uint8_t line_height;
    uint16_t glyph_count;
    const uint16_t *codepoints;
    const cyd_ui_font_glyph_t *glyphs;
    const uint8_t *bitmaps;
} cyd_ui_font_t;

/*
 * 16px regular: body text and notes. The UI character set, plus all of JIS
 * X 0208 when scripts/ui_fonts/font_profile.json asks for it (for text that
 * arrives at run time, such as a server message; docs/cyd_ui_fonts.md).
 */
extern const cyd_ui_font_t cyd_ui_font_body;
/* 16px bold: header titles and small buttons. Full UI character set. */
extern const cyd_ui_font_t cyd_ui_font_body_bold;
/* 24px bold: headings, main buttons and results. Full UI character set. */
extern const cyd_ui_font_t cyd_ui_font_title;
/* 48px bold: digits, ":/-. " and the result marks "✓!" only. */
extern const cyd_ui_font_t cyd_ui_font_clock_medium;
/* 64px bold: digits, ":/-. " and the result marks "✓!" only. */
extern const cyd_ui_font_t cyd_ui_font_clock_large;

/* Binary search; NULL when the font has no glyph for `codepoint`. */
const cyd_ui_font_glyph_t *cyd_ui_font_find_glyph(const cyd_ui_font_t *font, uint16_t codepoint);

/*
 * Decodes one UTF-8 sequence starting at `*text` and advances past it.
 *
 * English contract: never reads past a NUL. A malformed or truncated sequence
 * yields U+FFFD and consumes at least one byte, so a loop over a string always
 * terminates. Code points above U+FFFF also yield U+FFFD, matching the 16-bit
 * glyph tables.
 */
uint16_t cyd_ui_font_next_codepoint(const char **text);

/*
 * Horizontal advance of `text` in pixels: the sum of glyph advances. A missing
 * glyph counts as the width of a space, which is also how it is drawn.
 */
int32_t cyd_ui_font_text_width(const cyd_ui_font_t *font, const char *text);

/* Advance of one code point, with the same missing-glyph rule. */
int32_t cyd_ui_font_codepoint_advance(const cyd_ui_font_t *font, uint16_t codepoint);

/* One wrapped line: `length` bytes of the source text starting at `start`. */
typedef struct {
    uint16_t start;
    uint16_t length;
} cyd_ui_font_line_t;

/*
 * Breaks `text` into lines no wider than `max_px`, for at most `max_lines`.
 *
 * Rules, in order:
 *  - '\n' always ends a line.
 *  - Otherwise a line ends before the first character that would overflow.
 *  - A line never starts with closing punctuation or a small kana (、。」ッ ...):
 *    the character before it moves down with it.
 *  - A run of ASCII letters and digits is not split when an earlier space on
 *    the line can take the break instead.
 *  - Spaces at either end of a wrapped line are dropped.
 *
 * Returns the number of lines written. `truncated` (may be NULL) is set when
 * text remained after the last line. Lines never split a UTF-8 sequence.
 */
size_t cyd_ui_font_wrap(const cyd_ui_font_t *font,
                        const char *text,
                        int32_t max_px,
                        cyd_ui_font_line_t *lines,
                        size_t max_lines,
                        bool *truncated);

#ifdef __cplusplus
}
#endif

#endif
